// -*- C++ -*- generated by wxGlade 0.3.1 on Thu Jul 29 15:03:36 2004

#include "gene.h"

// Global variables are defined here for convenience.
/**
 * Global variables are defined here to make the code
 * more obvious (hopefully). All of the GUI code will
 * (hopefully) maintain the state of these variables?
 */
wxArrayString celFiles;
wxArrayString celTypes;
wxArrayString celFullPaths;

wxString defaultCDFDirectory;
wxString cdfFile;
wxString rmaOutputFile;

// Declare a simple application to start up a frame.
class MainApp: public wxApp 
{
public:
  bool OnInit();
  int OnExit();
};

wxApp *wxapp;

IMPLEMENT_APP(MainApp)

bool MainApp::OnInit()
{
  wxapp = this;
  argv  = wxapp->argv;

  wxInitAllImageHandlers();
  MainFrame *m_frame = new MainFrame((wxWindow *)NULL, -1, wxT(""));
  // Good place to Get Configstuff, then have frame get defaults.
  SetTopWindow(m_frame);
  m_frame->Show();
  return true;
}

	
int MainApp::OnExit()
{
  // Good place to have frame save defaults.
  return 0;
}
